version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

workflows:

  node-test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - "16.15"
                - "14.19"
                - "12.13"
          filters:
            branches:
              only:
                - circleci

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - heroku/deploy-via-git:
          app-name: joke-api-zak
          requires:
            - "node/test"
            - "node/run"
          filters:
            branches:
              only:
                - circleci